DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS seat;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  user_type TEXT NOT NULL, 
  ad_id TEXT NULL,
  rnk TEXT NOT NULL,
  phone_no TEXT NULL  
);

CREATE TABLE seat ( 
  seat_no TEXT PRIMARY KEY,
  floor TEXT NOt NULL,
  occu_id TEXT NULL,
  occu_date TEXT NULL DEFAULT CURRENT_DATE,
  occu_time TEXT NULL DEFAULT CURRENT_TIME,
  xpos INT NOT NULL,
  ypos INT NOT NULL
);



CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);